language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update

install:
  - composer install --prefer-source

script:
  - vendor/bin/phpunit
  
notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
